
####
GET http://localhost:8080/curso-api/index.php/cliente
####
GET http://localhost:8080/curso-api/index.php/producto
####
GET http://localhost:8080/curso-api/index.php/pedido
####
GET http://localhost:8080/curso-api/index.php/detalle-pedido
####


put http://localhost:8080/curso-api/index.php/cliente/12 HTTP/1.1
content-type: application/json; charset=UTF-8

{
    "clienNombre": "Cliente Test 12",
    "clienDireccion": "Direccion de test 12"
}

